# Generated by Django 5.0.6 on 2025-05-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوربین')),
                ('protocol', models.CharField(choices=[('mjpeg', 'MJPEG'), ('rtsp', 'RTSP'), ('http', 'HTTP')], max_length=20, verbose_name='پروتکل')),
                ('url', models.CharField(max_length=255, verbose_name='آدرس دوربین')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز عبور')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت دوربین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'دوربین خارجی',
                'verbose_name_plural': 'دوربین\u200cهای خارجی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد ملی')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'اشخاص',
            },
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_data', models.TextField(verbose_name='داده embedding')),
                ('model_name', models.CharField(default='VGG-Face', max_length=50, verbose_name='نام مدل')),
                ('face_analysis', models.JSONField(blank=True, null=True, verbose_name='آنالیز چهره')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to='face_api.person', verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'کدگذاری چهره',
                'verbose_name_plural': 'کدگذاری\u200cهای چهره',
            },
        ),
        migrations.CreateModel(
            name='RecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان تشخیص')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مکان')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('confidence', models.FloatField(default=0.0, verbose_name='میزان اطمینان')),
                ('analysis', models.JSONField(blank=True, null=True, verbose_name='آنالیز چهره')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_logs', to='face_api.person', verbose_name='شخص')),
            ],
            options={
                'verbose_name': 'لاگ تشخیص',
                'verbose_name_plural': 'لاگ\u200cهای تشخیص',
                'ordering': ['-timestamp'],
            },
        ),
    ]
