# Generated by Django 5.0.6 on 2025-04-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دوربین')),
                ('protocol', models.CharField(choices=[('mjpeg', 'MJPEG'), ('rtsp', 'RTSP'), ('http', 'HTTP')], max_length=20, verbose_name='پروتکل')),
                ('url', models.CharField(max_length=255, verbose_name='آدرس دوربین')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز عبور')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت دوربین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'دوربین خارجی',
                'verbose_name_plural': 'دوربین\u200cهای خارجی',
                'ordering': ['name'],
            },
        ),
    ]
